### ISSUE TITLE
Cannot install through pip or locally because of setup.py

### ISSUE THREAD

**Issue by Wigder** [indix/whatthelang#16]
When attempting to install:

`
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ser\AppData\Local\Temp\pip-req-build-jkgwiajx\setup.py", line 8, in <module>
        readme = f.read()
      File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 661: character maps to <undefined>
`

Fixed by changing the following lines from setup.py:
```python
with open('README.md'') as f:
    readme = f.read()
with open('LICENSE') as f:
    license = f.read()
```

To the following:
```python
with open('README.md', encoding='utf-8') as f:
    readme = f.read()
with open('LICENSE', encoding='utf-8') as f:
    license = f.read()
```

**Comment by Wigder** [comment]
Python ver is 3.6.8

**Comment by Wigder** [comment]
This is on Windows by the way - I realise now that this package is really difficult to install on Windows due to the C dependencies.

**Comment by omarmhaimdat** [comment]
I run into the same issue, it seems that one of the dependencies is deprecated, I'm not sure which one but if I would guess I would say it has to do with NumPy API.

**Comment by Elyesbou** [comment]
I'm still having the same issue while installing whatthelang on windows . any new updates concerning the solution? thanks

**Comment by sachin376** [comment]
Same issue. I have been struggling to install whatthelang on windows machine but no luck. Any update on this. thanks!

**Comment by MOvi996** [comment]
same issue. did anyone ever find a way to install it on windows?
