### ISSUE TITLE
setup failed 

### ISSUE THREAD

**Issue by mhndm** [indix/whatthelang#6]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7VI_fe/pyfasttext/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7VI_fe/pyfasttext/

**Comment by mhndm** [comment]
resolved after install :
pip install Cython --install-option="--no-cython-compile"

pip install numpy
